name: exchange_app
description: >- 
  A real-time currency exchange rate tracker built with Flutter. 
  Stay updated with the latest financial data and convert currencies effortlessly.

publish_to: 'none'

version: 1.0.0+1
repository: 'https://github.com/ultra-rony/exchange_app'
topics: [exchange, exchange-app, exchange-mate]

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.8
  dio: ^5.8.0+1
  flutter_bloc: ^9.1.0
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  logger: ^2.5.0
  auto_route: ^10.0.1
  injectable: ^2.5.0
  json_annotation: ^4.9.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  sqflite: ^2.4.2
  flutter_dotenv: ^5.2.1
  path: ^1.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.4
  auto_route_generator: ^10.0.1
  injectable_generator: ^2.7.0
  mockito: ^5.4.5

flutter:

  uses-material-design: true

  assets:
   - assets/
   - .env

flutter_intl:
  enabled: true
