name: Flutter CI/CD

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.29.2'

      - name: Install dependencies
        run: flutter pub get

      - name: Creating a test env file
        run: |
          echo "COINCAP_API_KEY=******" > .env
          echo "LOGIN=test" >> .env
          echo "PASSWORD=test" >> .env
        shell: bash

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test